### ISSUE TITLE
Agregar tests automaticos en el CI

### ISSUE THREAD

**Issue by FdelMazo** [FdelMazo/FIUBA-Plan#101]
Habría que asegurarse de que en cada push no se rompa el siu parser, que es el core de la herramienta y es facil de testear (y facil de romper con pequeños cambios).

Hay que probar parsear los distintos txts ([siu-usuario-exactas-computacion-primer-cuatri.txt](https://github.com/FdelMazo/FIUBA-Plan/files/14643294/siu-usuario-exactas-computacion-primer-cuatri.txt), [siu-fede.txt](https://github.com/FdelMazo/FIUBA-Plan/files/14643295/siu-fede.txt),  [siu-axel.txt](https://github.com/FdelMazo/FIUBA-Plan/files/14643306/siu-axel.txt) ) y asegurarse que los resultados sean equivalentes al objeto que queremos (cantidad de materias, cursos, las clases con los horarios definidos, etc)

**Comment by lopezac** [comment]
Te parece hacer los tests con Jest?

**Comment by FdelMazo** [comment]
Si! No tengo preferencias. Con que sea fácil de enganchar a lo que ya tenemos, por mi va bien

**Comment by lopezac** [comment]
Pensaba crear una branch tests directo en este repo, y abrir un pr draft con una tasklist inicial, de bancar estos archivos

**Comment by FdelMazo** [comment]
Buenísimo!
