### ISSUE TITLE
Plan compartido con permalink no carga en celular

### ISSUE THREAD

**Issue by lopezac** [FdelMazo/FIUBA-Plan#108]
Hola fede!, es raro pero el permalink de un plan funciona cuando lo abro desde mi computadora, pero al compartirlo con un amigo no le anduvo en el celular, y lo probe en mi celular y tampoco funciona, tampoco anda al recargar la pagina.

Lo probe en un Android con el Chrome y el Brave, con las materias del segundo cuatrimestre de este año.

[permalink_1.txt](https://github.com/user-attachments/files/16503809/permalink_1.txt)
[permalink_2.txt](https://github.com/user-attachments/files/16503810/permalink_2.txt)
[siu-guarani.txt](https://github.com/user-attachments/files/16503811/siu-guarani.txt)

**Comment by FdelMazo** [comment]
El finde lo reviso! Gracias Axel

**Comment by FdelMazo** [comment]
Hola @lopezac ! Me fije, y creo que el problema esta en el limite de tamaño de las URLs en los browsers en android, puede ser? Si te fijas, cuando intentas abrir el link en el celular, se copia hasta la secuencia `DsJ`, que es justamente el char 5000 de la URL.

- Habría que encontrar alguna manera de hacer mas cortas la URLs (con otro tipo de compresión del JSON)
- Habría que tener alguna manera de handlear URLs grandes cosa de que al menos te salte un cartel que diga "no se pudo cargar el permalink"

**Comment by lopezac** [comment]
Bueno fede hay intento implementarlo y te muestro que sale!

**Comment by lopezac** [comment]
Fede, investigando varias tecnicas de compresion, lo que pude ver es que la longitud actual que se logra al comprimir con pako y gzip es de 8800 caracteres (de mi oferta de comisiones almenos), y lo que llegar a comprimirlo utilizando otras tecnicas de compresion (lzma, o msgpack con pako) es a 7200 caracteres, que no creo que sea muy util.

Propongo que si al entrar a un permalink que la app detecte si esta en un sistema android, y si lo esta y el permalink tiene una longitud mayor a 5000 caracteres, redirectear al home indicando (con un tooltip?) que "no se pudo cargar el permalink" o algo asi. Que opinas?

**Comment by FdelMazo** [comment]
Si, me parece bien eso. No agrega nada cambiar el compresor (y te quema los links existentes encima).

Para mi directamente no preguntes si es android o no. Con clavarle un try/catch al cargador de permalink (y ya que estamos, al de savedata) debería funcionar. Si levanta bien las cosas, todo cool, si levanta mal, tirar un toast cortito que diga "El plan no se pudo cargar correctamente, si estas desde un celular probalo desde la compu" (o cualquier fraseo que te pinte).

**Comment by lopezac** [comment]
Me parece perfecto Fede ahi lo implemento

**Comment by FdelMazo** [comment]
Lo que me refería del savedata es otro issue, que no se bien como debuggear. Creo que en algun lado esta fallando el setting y getting del local storage y puede que este haciendo que se rompa algo. Lo que me gustaría es que, similar a este feature, cuando falla algo directamente te vuelvas al home y no te crashee la pagina.

Me cargaron esto:

> "Hola! Como estas? En mi plan fiuba borre los horarios del siu y se volvio la pantalla blanca, y ahora cada vez que entro directamente no carga. 
Desde ya muchas gracias y espero que estes bien!!
Saludos"

Cuando la pagina esta en blanco en react significa que hubo un error no atrapado. La solucion caotica es ponerle un catch all a la pagina y hacer que si falla algo se limpie el storage y se rediriga a la home. Pero algo un poco mejor sería encontrar donde esta fallando el manejo del json del local storage (puede que sea algun json parse, el `removehorariossiu`, el `getfromstorage`, no estoy seguro, no lo intente replicar todavia).

Nada, lo dejo a modo de comentario por si se te ocurre que puede ser Axel, pero no lo veo muy urgente, y tampoco lo decía a modo de encajartelo a vos para que lo fixees!

**Comment by lopezac** [comment]
Del bug que te mandaron, no logre replicarlo, pero por lo que veo en DataContext hay 2 JSON.parse (se podria hacer una unica funcion que haga JSON.parse y ahi metemos el try catch) que no se esta catcheando (try catch) si salta un error (osea que se le pase un string que sea un JSON invalido),

Y el valor que se guarda en el localStorage es el savedata (asi que el json invalido vendria capaz de los 5 propiedades de savedata, selectedMaterias, horariosSIU, etc)

Asi que me parece q el problema del savedata una forma de "solucionarlo" temporalmente (no seria solucionar el problema real como decis, pero almenos se romperia menos la pagina)

Seria haciendo como decis que si salta un error parseando json redireccionar al home y limpiar el storage, como hacemos con el permalink.
