### ISSUE TITLE
[Mobile] Cambio de vista

### ISSUE THREAD

**Issue by NachoRaik** [FdelMazo/FIUBA-Plan#13]
Una boludez de UX pero que me parece que se podría tunear es el cambio de vista adentro del panel de agregado. 
Me parecería mas intuitivo si estuviese anclado en la pantalla general (lo mismo si en algun momento llegase a haber un light/dark switch).

Trato de probarlo estas semanas a ver cómo queda y mando screen a ver que les parece.

**Comment by FdelMazo** [comment]
+1 a la idea. Hay que estar en sync con lo que va pasando en #23 para que los botones de dark mode y mobile view  (y tal vez de abrir drawer) esten juntos, sean adentro o afuera del drawer.

Lo más importante acá me parece que es mantener la mayor cantidad de espacio de pantalla para el usuario, y no invadirle mucho. En particular porque la idea es que se pueda usar en celulares con pantalla chica, y que se use donde se use, sea muy screenshoteable el horario, para compartirlo.

**Comment by FdelMazo** [comment]
Lo termine dejando en el drawer, quise mantener la pantalla lo mas screenshoteable posible
