### ISSUE TITLE
Horario de 9119 Economia para electronicos

### ISSUE THREAD

**Issue by santi54gc** [FdelMazo/FIUBA-Plan#15]
Hola aviso que el horario esta mal en el siu y en el organizador. Los profesores avisaron que seguirá siendo los martes a la misma hora como viene siendo hace varios cuatrimestres.
Saludos

**Comment by FdelMazo** [comment]
Por ahora, nos vamos a mantener siempre en sintonia con el SIU, para evitar entrar en líos como este (que no es un caso aislado) y siempre comunicar lo mismo que comunica FIUBA.

En un futuro, tal vez, se permite más edición de parte del usuario (agregar las propias actividades extracurriculares, o eliminar las clases que quiera)
