### ISSUE TITLE
Materias Combobox doesn't keep state 

### ISSUE THREAD

**Issue by FdelMazo** [FdelMazo/FIUBA-Plan#18]
Al escribir una materia en el combobox, la busca correctamente. Entonces, por ejemplo, busco `ana`, me aparecen todas las materias que comienzan con analisis, y agrego una.

Bien, despues de agregarla, yo debería poder clickear en el combobox (que todavia tiene el `ana` escrito) para seguir buscando materias, y las que me aparecen para seleccionar **deberían** ser las que ya estaban antes. Esto no pasa, lo que termina pasando es que hay que forzar al usuario a tener que escribir algo nuevo en el combobox para que muestre las materias correctas.

**Comment by komod0** [comment]
Fijate que onda el fix, yo la verdad que estoy super limitado con react para hacer algo mas elaborado

**Comment by nicomatex** [comment]
Yo estuve peleando un rato pero no logre hacerlo funcar, a ver

**Comment by komod0** [comment]
#21 Me di cuenta que metí la pata tremendamente, arregla eso pero rompe otras cosas(el checkmark que se le pone a las materias seleccionadas entre otras cosas), de lo que entiendo lo que esta pasando es:
- Cuando se hace click sobre la materia a agregar se llama a agregarMateria, esto modifica `data` por lo que se llama a useEffect de SelectMateria
- Esto hace que se resetee la lista de materias que se muestra como resultado de la busqueda a todas las visibles (`setInputItems(materiasVisibles);`)

Esto ultimo no debería pasar porque se quieren mantener los resultados de la busqueda.

**Comment by FdelMazo** [comment]
Fixeado en 89f5376d76c6f5b79757b4faaade4d73005d0aad !
