### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by nicomatex** [FdelMazo/FIUBA-Plan#23]
Pinta agregar ese Dark Mode al calendario?

**Comment by komod0** [comment]
YES, el otro día estaba chusmeando algo de eso, por lo que vi hay varias formas de hacerlo, esta guía esta bastante bonita:
https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/

**Comment by nicomatex** [comment]
Justo estaba indagando un poco! Tome el approach de usar dos stylesheets separadas, y dos theme.js diferentes, tipo 
![image](https://user-images.githubusercontent.com/3434572/93271261-392c3480-f789-11ea-9e9d-37dc8698cbb3.png)

Para que quede algo asi 

![image](https://user-images.githubusercontent.com/3434572/93271310-5234e580-f789-11ea-9c7a-4c74361fdab4.png)

**Comment by komod0** [comment]
Esta bueno, yo me habia puesto a jugar modificando el css desde la consola y llegue a algo parecido, pero se me hacia medio raro el contraste que hay entre las celdas grises y las mas oscuras asi que lo termine sacando directamente y me quedo algo asi:
![darkmodo](https://user-images.githubusercontent.com/21377494/93274528-f5d5c400-f790-11ea-995d-784507d9f343.png)

**Comment by komod0** [comment]
Me di cuenta que el calendario de teams de microsoft usa un estilo super parecido para los eventos y les queda algo asi el modo oscuro:
![teams](https://user-images.githubusercontent.com/21377494/93274704-51a04d00-f791-11ea-81ca-67981f3d6ffb.png)

**Comment by nicomatex** [comment]
Si, la verdad que queda mejor asi. Voy a ver si puedo lograr una primera version y la pusheo a la noche!

**Comment by FdelMazo** [comment]
Creo que la manera correcta de implementar el dark mode sería utilizando el hook de chakra: https://chakra-ui.com/color-mode

El único cuidado a tener aca es que el estilo es un choclo... Tenemos cosas tiradas en theme.js, cosas hardcodeadas inline como la prop `style` de los componentes, y cosas en Style.css que es css puro (más que nada para estilar el react-big-calendar.

Si conseguimos una manera de unificar eso y no repetirse, va como piña el hook.

(ot: hermoso el chusmear el de microsoft. Me parece que el estilo de las rayitas en el border left de los eventos pueden ser copadas para diferenciar eventos (maybe con rayitas == teorica, sin rayitas == practica, o algo con las distintas sedes, o solo para mostrar que hay overlap). Idem me parece copado el botoncito de sync abajo a la der, solo que no tenemos cosas copadas para hacer onclick sobre la materia. (un boton de remover materia ahí seria un choclo imo))

**Comment by FdelMazo** [comment]
(Ojo, un botoncito abajo a la der de cada evento que sea algo como "No la voy a cursar" y te remueva ese evento (solo la clase, no la materia), va como piña. Para esas materias que "a las teoricas no hace falta ir")

Anyway, si hay quorum, hay que llevarlo a un issue nuevo

**Comment by nicomatex** [comment]
Un amigo me acaba de sugerir exactamente lo mismo hace 15 minutos! Lo agrego como issue porque parece que seria util (tambien hay algunas materias que aparecen en 2 dias, pero que uno _elige_ que dia cursarla). Agrego el issue

**Comment by FdelMazo** [comment]
offtopic movido a #23

**Comment by FdelMazo** [comment]
En 89f5376d76c6f5b79757b4faaade4d73005d0aad implemente esto @nicomatex @komod0 

La verdad, no me parece que haya quedado muy lindo el general view, siento que pequé de minimalista, pero la agenda me gusto. Acepto PRs para dejarlo mas lindo!!

![image](https://user-images.githubusercontent.com/25667102/129480166-755d0f8f-4107-4d94-ad5c-c040df770d62.png)

![image](https://user-images.githubusercontent.com/25667102/129480206-45532701-4f69-4cdd-a56c-68c4e3627b66.png)
