### ISSUE TITLE
Remove Class Individually Button

### ISSUE THREAD

**Issue by nicomatex** [FdelMazo/FIUBA-Plan#24]
Un botoncito (o algo similar) abajo a la derecha de cada evento para remover ese evento particular (y no todos los eventos o clases del curso. Solo esa)

**Comment by FdelMazo** [comment]
Mi único miedo con estos cambios es que empiece a bloatear la app y termine siendo un spaghetti de codigo y features (como le paso a su hermana boba... el FIUBA-Map). Mientras mas poder de edición se le de al usuario, mas jodido va a ser mantener el estado. 

Porque después de esto, el otro feature que nos fueron pidiendo es un "Dejame agregar mis propias actividades, para poder poner mis clases de karate y tenerlas en la misma app"... y así empieza a crecer y crecer. (ojo, no estoy en contra de esta idea, solo que si agregas un -, también sería lo mejor agregar un +). Como sucedió en #15 

Si hay manera limpia de hacerlo, +1. Si no, imo wont-do. 

(Also, no se que tan facil es agregar un boton en cada evento en sí. Si se que es facil agregar cosas onClick del evento, lo cual podria promptear un "remover esta clase?").

Antes que mandarse a codear, habría que pensarlo bien si vale la pena!

**Comment by nicomatex** [comment]
Si, absolutamente. Creo que por lo pronto queda medio en la icebox este cambio (mis habilidades reactosas por lo pronto tampoco me permiten ver cómo lo haría je).

**Comment by FdelMazo** [comment]
Done en fcf9a0db15a55e4f6da627b43853eed2a028fd01

Hay un botoncito de 'no cursar' que le pone un background gris. Sencillo? si. Choto? tal vez.

![image](https://user-images.githubusercontent.com/25667102/129482993-51a72934-4e54-4b9d-8d03-9a020afe6e76.png)
![image](https://user-images.githubusercontent.com/25667102/129483002-23a7a39d-271e-4b79-9772-72793ade4314.png)
