### ISSUE TITLE
Get statistics of courses from DollyFiuba

### ISSUE THREAD

**Issue by verosupervero** [FdelMazo/FIUBA-Plan#27]
Dolly has several comments and statistics that would be useful to people to know about to manage their schedule, for example:
1-One schedule has 5 points for Sirne, 4 for Cabrera and 5 for Vargas. The total points of the shedule is 14/15 => so the schedule is very nice. 
2-People would like to see if the course is nice not only by the rate, but by their comments. 
3- People would like to compare several plans by its points.
"Save plan 1 and compare to plan 2".

**Comment by FdelMazo** [comment]
(la seguimos en español)

La verdad, no estoy 100% seguro de esta idea. Si hay una interfaz cómoda para ver los números, se puede repensar, pero como siempre, hay que cuidar no bloatear la app.

¿Como podría ser la integración?
