### ISSUE TITLE
Búsqueda de materias sin unicode

### ISSUE THREAD

**Issue by alancito10t** [FdelMazo/FIUBA-Plan#31]
El buscador de materias diferencia entre _química_ y _quimica_ al momento de buscar, y otras asignaturas con tilde en sus nombres. Si esto se podría modificar creo que podría mejorar mucho la experiencia en el sitio.

**Comment by FdelMazo** [comment]
Uf, que bodrio. Gracias! Veo si lo puedo modificar!

**Comment by FdelMazo** [comment]
Solucionado en e5bd552347edddf401a2c75fd88c62ce5976c3f9 !
