### ISSUE TITLE
El guardado es automático

### ISSUE THREAD

**Issue by nazar9318** [FdelMazo/FIUBA-Plan#36]
¿Podría ser opcional en caso de que uno quiera probar nuevas combinaciones y se olvide de retroceder?

**Comment by FdelMazo** [comment]
Hola @nazar9318 , disculpame, acabo de ver esto y tu otro issue.  Seguro en estas semanas le ponga un poco mas de ganas a este repo y empiece a rediseñarlo un poco

Respecto al guardado, tal vez se puede poner un boton de 'limpiar catedras' para resetear y empezar desde cero, pero el guardado automatico quiero mantenerlo porque es algo que gusta bastante

**Comment by nazar9318** [comment]
No hay problema.
El del botón de resetear me parece muy buena idea.

**Comment by FdelMazo** [comment]
Agregué un botón de `Resetear Catedras` en el drawer, en b9df86eb565a49ecb506f4f5123f09f2e67d7aa4


![image](https://user-images.githubusercontent.com/25667102/129480269-084c1067-9bfd-43e7-8eb2-4254d38a1347.png)

Si no te gusta como quedó, reabrime el issue!
