### ISSUE TITLE
Combinaciones de horarios

### ISSUE THREAD

**Issue by nazar9318** [FdelMazo/FIUBA-Plan#37]
Si mal no recuerdo hace unos años el organizador tenía propuestas de horarios en base a la cantidad de materias que quiera hacer uno y cantidad de horas superpuestas aceptadas, ¿podría implementarse de vuelta?

**Comment by FdelMazo** [comment]
Se puede pensar! Creo que es un re quilombo, pero voy a buscar alguna manera de hacerlo andar. Por ahora dejo abierto el issue y si veo que no esta dentro del scope del proyecto, lo cierro

**Comment by FdelMazo** [comment]
Después de mucho pelotear, no pude hacer esta funcionalidad. Disculpa! Acepto algun futuro PR que la agregue, pero por ahorra cierro el issue

**Comment by FdelMazo** [comment]
Lo reabro. Algun dia me va a salir hacerlo andar

**Comment by FdelMazo** [comment]
Okey, ideas al azar: 

Front:
- En algun lugar del sidebar hay boton que te abre el `randomizador` (encontrarle nombre lindo) (also, podria tener alguna descripcion linda..)
- Tal vez un help arriba a la derecha que en hover prenda el tooltip y explique como funciona esto?
- Eso te cierra el sidebar y te abre el modal del organizador (abajo a la izq? abajo a la der?) (comportamiento como el modal de sugerencias)
- El modal tiene 2 parametros que configuras: N materias (o number inputo o slider de chakra) y Xhs de solapamiento que te bancas (slider probablemente)
- Marcas esos parametros y empezas a tocar botones de Next y Back hasta encontrar uan combinacion que te guste
- hay que tneer boton de submit ( ✅ ) y de close ( ❌ ) porque va que haber que commitear la combinacion elegida
- Hay que simbolizar mejor lo de que las materias clickeadas 'no se cursan', porque actualmente clickeas una materia y no sabes lo que paso
- Las materias actualmente randomizadas hay que diferenciarlas de las que ya estan seteadas. tal vez las seteadas son 'solidas' mientras que las randomizadas son mas temporales y se ven mas fantasmita
- Si estas randomizando materias, y te gusta una catedra, queres poder clickearla para que se solidifique y quede. y tambien supongo que desclickearla (nice to have)
- Un progress bar que diga cuantas opciones vamos de todas las posibles...

Back:
- Las materias ya seleccionadas antes de abrir el modal no se randomizan, son las que dijiste que querias cursar
- Si clickeas una clase, se marca como 'no cursar'. Estas clases no se cuentan para el solapamiento!
- Mientras estas en modo randomizador, las materias randomizadas tienen el atributo `temp: true` que es lo que dice que no commitees en el session storage esa materia, y mostrala mas ghosteadita. cuando el usuario toca en commit, se saca el atributo a las materias
- Hay que tener cuidado con la performance. siento que pedir una combinacion de N cosas va a romper la computadora. Seguro hay algun algoritmo de solapamiento copado y eficiente en esta vida

**Comment by FdelMazo** [comment]
Bueno, habiendo dicho todo esto y volviendome loco con como implementarlo, voy a dejar de lado este issue (y acepto ideas, siempre). Me conformo bastante con agregar nada mas un indicador que me dice que un curso esta overlappeando con el resto del plan, agregado en 56595ed5141e1c05a27635b9085f8a96d55f60f2

**Comment by FdelMazo** [comment]
Cual es mi mayor problema con la implementacion del combinador de horarios? que si tenes ganas de cursar analisis 2 y proba (por decir dos materias con mucha oferta horaria), las combinaciones posibles son mas de 100, y si le presentas al usuario esas 100 combinaciones, la verdad es que nunca va a verlas todas. Es decir, no encuentro la mejor estructura para presentar tantas combinaciones de horarios. Habria que encontrar alguna forma inteligente de agruparlas tal vez, para que en vez de tener 100, tengas 15 con la misma idea (por ejemplo, agrupar todas las combinaciones que cubren el mismo rango horario, sin importar que catedra es). O, tal vez es mas inteligente mostrar los sobrelapamientos directamente, es decir, que catedras NO se pueden juntar nunca.

Pero bueno, lo que si llegue a codear es el front, que es basicamente un modal que te pregunta cuantas materias queres cursar, y con cuanto solapamiento: 
<img width="416" alt="image" src="https://user-images.githubusercontent.com/25667102/147575506-9a6ca7af-f744-4b33-a462-378a6b3a86b8.png">

<details>
<summary>Codigo</summary>

```
const grynbotToast = React.useRef();
const [nMaterias, setNMaterias] = React.useState(selectedMaterias.length);
const [superposicion, setSuperposicion] = React.useState(0);

---

const D20Icon = () => (
  <Icon boxSize={5} viewBox="0 0 480 512">
    <path
      fill="currentColor"
      d="M106.75 215.06L1.2 370.95c-3.08 5 .1 11.5 5.93 12.14l208.26 22.07-108.64-190.1zM7.41 315.43L82.7 193.08 6.06 147.1c-2.67-1.6-6.06.32-6.06 3.43v162.81c0 4.03 5.29 5.53 7.41 2.09zM18.25 423.6l194.4 87.66c5.3 2.45 11.35-1.43 11.35-7.26v-65.67l-203.55-22.3c-4.45-.5-6.23 5.59-2.2 7.57zm81.22-257.78L179.4 22.88c4.34-7.06-3.59-15.25-10.78-11.14L17.81 110.35c-2.47 1.62-2.39 5.26.13 6.78l81.53 48.69zM240 176h109.21L253.63 7.62C250.5 2.54 245.25 0 240 0s-10.5 2.54-13.63 7.62L130.79 176H240zm233.94-28.9l-76.64 45.99 75.29 122.35c2.11 3.44 7.41 1.94 7.41-2.1V150.53c0-3.11-3.39-5.03-6.06-3.43zm-93.41 18.72l81.53-48.7c2.53-1.52 2.6-5.16.13-6.78l-150.81-98.6c-7.19-4.11-15.12 4.08-10.78 11.14l79.93 142.94zm79.02 250.21L256 438.32v65.67c0 5.84 6.05 9.71 11.35 7.26l194.4-87.66c4.03-1.97 2.25-8.06-2.2-7.56zm-86.3-200.97l-108.63 190.1 208.26-22.07c5.83-.65 9.01-7.14 5.93-12.14L373.25 215.06zM240 208H139.57L240 383.75 340.43 208H240z"
    />
  </Icon>
);

---

<Flex row justifyContent="space-around" mb={2}>
  {!!selectedMaterias.length && (
    <Button
      borderColor="primary.300"
      borderWidth={1}
      leftIcon={<D20Icon />}
      colorScheme="primary"
      variant="ghost"
      fontSize="sm"
      onClick={() => {
        onClose();
        toast.close(grynbotToast.current);
        return (grynbotToast.current = toast({
          render: (props) => (
            <Alert
              borderRadius={6}
              p={10}
              mb="3em"
              borderColor="primary.300"
              borderWidth={2}
              bg="drawerbg"
              color="white"
              opacity={0.8}
              _hover={{ opacity: 1 }}
            >
              <Flex direction="column">
                <AlertTitle fontSize="xl">
                  Hola, soy Grynbot!
                </AlertTitle>
                <AlertTitle>
                  Mitad Grynberg · Mitad Robot
                </AlertTitle>
                <AlertDescription
                  display="flex"
                  p={2}
                  m={4}
                  justifyContent="space-between"
                >
                  <Flex
                    direction="column"
                    mr={8}
                    alignItems="center"
                  >
                    <Text my={2}>Materias</Text>
                    <NumberInput
                      w="9ch"
                      defaultValue={nMaterias}
                      min={1}
                      max={selectedMaterias.length}
                      onChange={setNMaterias}
                    >
                      <NumberInputField />
                      <NumberInputStepper>
                        <NumberIncrementStepper />
                        <NumberDecrementStepper />
                      </NumberInputStepper>
                    </NumberInput>
                  </Flex>
  
                  <Flex
                    direction="column"
                    ml={8}
                    alignItems="center"
                  >
                    <Text mt={2} mb={4}>
                      Superposición (hs)
                    </Text>
                    <Slider
                      defaultValue={superposicion}
                      max={3}
                      step={0.5}
                      onChangeEnd={setSuperposicion}
                    >
                      <SliderMark
                        value={0}
                        fontSize="sm"
                        mt="1"
                        ml="-1"
                      >
                        0
                      </SliderMark>
                      <SliderMark
                        value={1}
                        fontSize="sm"
                        mt="1"
                        ml="-1"
                      >
                        1
                      </SliderMark>
                      <SliderMark
                        value={2}
                        fontSize="sm"
                        mt="1"
                        ml="-1"
                      >
                        2
                      </SliderMark>
                      <SliderMark
                        value={3}
                        fontSize="sm"
                        mt="1"
                        ml="-1"
                      >
                        3
                      </SliderMark>
                      <SliderTrack>
                        <SliderFilledTrack />
                      </SliderTrack>
                      <SliderThumb boxSize={2} />
                    </Slider>
                  </Flex>
                </AlertDescription>
  
                <Button
                  mt={4}
                  alignSelf="center"
                  borderColor="primary.300"
                  borderWidth={1}
                  leftIcon={<D20Icon />}
                  colorScheme="primary"
                  variant="ghost"
                  onClick={() => {}}
                >
                  Calcular
                </Button>
              </Flex>
              <CloseButton
                color="primary.500"
                onClick={() => toast.close(props.id)}
                position="absolute"
                right="8px"
                top="8px"
              />
            </Alert>
          ),
          status: "info",
          position: "bottom-left",
          duration: null,
          isClosable: true,
        }));
      }}
    >
      Grynbot
    </Button>
  )}
</Flex>

```

</details>

**Comment by FdelMazo** [comment]
Toda persona es bienvenida a codear esto!
