### ISSUE TITLE
Horarios Extracurriculares

### ISSUE THREAD

**Issue by mpata2000** [FdelMazo/FIUBA-Plan#42]
Tener la opción de poder agregar horarios extracurriculares semanales para deportes, trabajo, estudios fuera de FIUBA, etc... Estaría bueno que sea algo que le pones un nombre, elegís la banda horaria y los días que queres que aparezca.

**Comment by FdelMazo** [comment]
Genial la idea. Aunque al principio estaba medio en contra de agregarla (me parece que bloatea un toque la app), ya me lo pidieron varias personas. No deberia ser jodida de implementar. Para la tanda de features del cuatri que viene estaria bueno meterla

**Comment by FdelMazo** [comment]
Implementado en 757399ecceea48b2d6a96ac8400961006bb61ca2 !
A tan solo dos dias de navidad
