### ISSUE TITLE
Sugerencia Cambio de colores

### ISSUE THREAD

**Issue by igonzalezbig** [FdelMazo/FIUBA-Plan#43]
Primero que nada esta muy bueno y funciona re bien. La sugerencia es que estaria bueno poder cambiar los colores de las materias, porque hay casos que se repiten varios colores.

**Comment by FdelMazo** [comment]
Gracias por la idea! los colores los quiero mantener asi quedan universales (por ejemplo, para cuando le mandas una foto de tu mapa a tu amigo), porque simbolizan las distintas cosas (aprobada, en final, etc). Pero si quiero que sean super distinguibles entre si.

O sea, me gusta la idea de que cada color sea un grupo distinto. El grupo de las materias aprobadas, el grupo de las materias electivas, y demas

Donde te paso que se repitan los colores?

**Comment by igonzalezbig** [comment]
Me paso a principio de cuatrimestre que estaba planificando los horarios y se repetían colores con diferentes materias. Lo que me gustaría es que cada materia tenga un color diferente para que sea mas fácil diferenciarlas.
 
Por ejemplo ahi Física y Análisis Numérico tienen el mismo color; y Intro tine uno muy parecido.
![image](https://user-images.githubusercontent.com/63425840/134399212-f9abd239-0431-41cf-b3ec-4975f062518a.png)

Mi sugerencia era que se pueda elegir colores que no se parezcan tanto.

**Comment by FdelMazo** [comment]
UF. Soy un re boludo, pense que este era un bug del fiuba map, no del fiuba plan. Por eso me parecia tan raro el issue, porque ahi no encontre mucho lio de colores.... desmerece enteramente mi ultimo comentario en este hilo!!

**Comment by FdelMazo** [comment]
Bueno, ahora si, volviendo al tema. Si, definitivamente tengo que mejorar la dispersion de colores. Lo que sucede en este momento es que quiero mantener que todas las catedras tengan un color unico, cosa de que si yo te comparto a vos una foto de mi plan, y vos y yo cursamos en la misma catedra, nos demos cuenta facil. 

En este momento lo que se hace es hashear los docentes a un color en hexa con https://github.com/zenozeng/color-hash

Voy a pensar alguna manera de que queden mas dispersos los colores, tal vez dividiendolos por departamento. Algo asi como que el depto lo hasheo a los primeros dos caracteres del color en hexa, los siguientes dos caracteres salen del codigo de la materia, y los ultimos dos caracteres salgan de los docentes.

Ojo, tal vez es mejor directamente usar los colores en HSL. El codigo de la materia se hashea a un HUE, y los docentes te dan un offset desde ese color de +-30. Siendo 360 los posibles HUEs, debería quedar bastante disperso. Jugas un poco con la lightness para que siempre quede legible, y estas

(Tambien tengo que jugar con los parametros de color-hash, que seguramente me esta devolviendo colores muy parecidos)

(y tengo que dejar de hacer que los colores se persistan en el session storage, para evitar que si yo cambie como se generan los colores, un usuario este usando los colores viejos todavia)

**Comment by FdelMazo** [comment]
En fin, gracias por el issue @igonzalezbig ! Para el cuatri que viene intento mejorar esto, para la nueva tanda de features de la app

**Comment by FdelMazo** [comment]
Última pregunta, veo que en tu screenshot tenes raros los tildes de los titulos de las materias. Te pasa en otras paginas esto? Me decis tu browser y sistema operativo, asi intento debuggearlo?

**Comment by igonzalezbig** [comment]
Lo de los tildes no lo note en otras paginas, capaz ocurre pero no me di cuenta. En este momento estoy en windows 10 y uso Brave browser.

**Comment by FdelMazo** [comment]
La realidad es que no hay manera inteligente de mejorar la separación de colores (sin cambiar la funcion de hash a algo mas uniforme).

Lo mejor que pude hacer es agrandar el abanico y hacer que se puedan elegir mas colores aca: 41ca135255a01fc257f2d8f2f96e9cde748a4561
