### ISSUE TITLE
Organizado el cuatrimestre que se pueda descargar el "plan" y/o enlazar con el calendar

### ISSUE THREAD

**Issue by julitaras** [FdelMazo/FIUBA-Plan#54]
- Estaria bueno poder descargar el plan que se hizo para el cuatrimestre, ya sea para que luego se pueda imprimir o poner de algun fondo de pantalla.

- Tambien que exista la posibilidad de agregar estos horarios al google calendar.

**Comment by FdelMazo** [comment]
@julitaras vieja querida amiga, gracias por el issue.

> Estaria bueno poder descargar el plan que se hizo para el cuatrimestre

Tal vez pasarlo a PDF? La verdad que no me llama mucho la idea de 'imprimir' el fiuba plan, la idea es que sea interactivo! Me pidieron lo mismo del fiuba map, y siento que rompe enteramente la idea de que sea una aplicación!

Hoy por hoy, un screenshot del fiuba plan entero debería funcionar para todo lo que se necesite!

> Tambien que exista la posibilidad de agregar estos horarios al google calendar.

Esto sí me gustaría, pero nunca supe como implementarlo! Porque tendrías que hacer que sea un evento recurrente desde X día hasta Z día, y eso haría que haya que hardcodear en algun lado los dias de inicio y fin de cursada, que cambian todo el tiempo... darle bola a los feriados, etc. Sumado a que ya muchas materias estan ofreciendo el propio google calendar, para despues poder clavar el google meet ahí, y esto solo agregaría duplicados molestos.

---

Siento que son dos issues muy dificiles de implementar bien, si me ayudas a pensar un poco los detalles de implementación, vemos de hacerlo! pero por ahora, no me copan enteramente

**Comment by FdelMazo** [comment]
Tal vez @JDSanto tiene alguna opinion al respecto? que me acuerdo que le gustaba la idea del calendario

**Comment by FdelMazo** [comment]
Kill por inactividad
