### ISSUE TITLE
Exportar (y porque no, importar) Planes 

### ISSUE THREAD

**Issue by Fxusto** [FdelMazo/FIUBA-Plan#59]
Estaria genial poder exportar los planes que armas, podrian exportarse como una hoja de excel o en su defecto en json. Pero para poder almacenarlos de alguna forma. 

Dejo esto por si es de algun tipo de ayuda. https://www.npmjs.com/package/react-export-excel

**Comment by FdelMazo** [comment]
Hola @Fxusto ! 

Gracias por el issue. Me ayudas a entenderlo mejor? Cual sería un contexto en el que necesite exportarlo? decis para luego poder volver a cargarlos en el Fiuba Plan, o para tenerlo como json/excel y llevartelo a otro lado? 

En este momento el plan se guarda en tu browser session, entonces cada vez que entres desde la misma PC vas a ver el mismo plan. No se me ocurre bien para que pasarlo a otra plataforma! En un json me parece que es bastante ilegible, y si es cuestion de tenerlo en el celu, creo que podria tranquilamente pasarse por screenshot.

Tal vez guardar todo el plan en un hash, cosa de que puedas copiar y pastear esa cadena en el fiuba map y se te re-hace el plan?

**Comment by Fxusto** [comment]
La idea de hashearlo esta buena me parece hasta mas practico, mas que nada lo pensaba para poder compartirlo sin tener que sacar screenshot y perder el dinamismo de poder seguir modificando cosas. Ya sea para compartirlo con otra persona o poder tenerlo en otra PC sin tener que volver a armar todos los planes desde cero.

**Comment by FdelMazo** [comment]
Genial che! Dejo el issue abierto y pienso alguna forma intuitiva de meterlo. No creo poder darle bolilla pronto. Si te animas, mandate y codealo! Los PRs son siempre bienvenidos

**Comment by FdelMazo** [comment]
Realmente no la veo sencilla la de compartir un plan así como así. En particular conflictua bastante con lo que el usuario ya tiene en su cache del browser.

Digo, imaginemos un usuario que tiene su plan de informatica en su browser. Un amigo le manda su plan de industrial para mostrarle lo que va a cursar. Que haces ahi? Juntas ambos, pisas uno, etc... Es dificil!

Encima, te cae el plan de industrial, y de la nada tenes que re-armar el resto de la app para que tenga sentido! El plan de industrial van a ser N cursos, pero en el sidebar de la derecha tenes que poner ahora las M materias para que puedas editarlas, y eso va a ser un bardo!

Entonces pienso... y si se comparte en read-only un plan? 

- Tocás un botón `Compartir Plan`
- Eso te copia al portapapeles algo asi como `fede.dm/FIUBA-Plan?share=104ab42f11`
- Ese hash corto (`104ab42f11`) es nada mas una secuencia de _cursos_,  y solo del tab actual. Es decir, no podes compartir un 'mira, tengo de opcion 1 cursar fisica2, y de opcion2 cursar algebra'. Cada tab es un hash distinto
- Ese link se lo pasas a un amigo/te lo guardas al celular.
- Cuando abris ese link, no entras a tu fiuba plan normal, con tu cache y demas. Directamente vas al fiuba plan que sea casi un calco del plan que te pasaron, sin ningun tipo de funcionalidad. No podes abrir tabs, no podes abrir el sidebar de la derecha, no te rompe lo que tenes en tu browser. (esto ultimo implica que tenes que llenar todo el codigo de `if share... disable control`

y ahora la pregunta del millon. Realmente tiene valor esto? es exactamente la misma funcionalidad que sacarle un screenshot a tu plan y guardartelo en el celular!

Que opinas @Fxusto ?

**Comment by julitaras** [comment]
Yo creo que esta bien si es una especie de readonly, ya que es el plan de uno y el otro quizas omite alguna opinion. O en caso de que se quiera con mas permisos uno decida (esto probablemente sea ir muy lejos). 

Ejemplo:
Queria compartirle a un amigo los planes que tenia en caso de aprobar el final de una materia, pero eran muchos planes.... por lo que el screen se me volvio una verdadera paja, ya que eran varias opciones. Entonces si hubiese algun tipo de share estaria piola. Quizaas estaria piola lo que mencionas que tiene el fiuba map para que ademas este syncronizado con el resto de los dispositivos

**Comment by julitaras** [comment]
Me conformo con el readonly 😆

**Comment by FdelMazo** [comment]
Bueno... termine haciendo algo medio raro con el local storage y las URL compartibles. Agregué este botón al sitio, en ed885da811ced7b55e48617382c44c9bc5af8715: 
![image](https://user-images.githubusercontent.com/25667102/220223574-4f595b9a-4162-4de7-bf72-8611166686fd.png)

@julitaras @Fxusto Tienen ganas de probar este _exageradamente beta_ feature? Es clickear el boton, y compartirle la URL a algún otro dispositivo/amigo y rezar que ande todo

**Comment by Fxusto** [comment]
Estos días lo estuve probando, tanto para pasarme planes entre PC y PC como con un par de compañeros para compartirnos los planes y funciona bien. A veces cuando ya estas en fede.dm/FIUBA-Plan/ y pegas el permalink nuevo hace falta recargar la pagina para que lo tome, pero supongo que eso tiene que ver con algo del browser. Me gusta que este el alert con el permalink actual para no perderlo pero al principio me pareció que quedaba un poco agresivo por el link con el hash tan largo. En general me gusta como lo resolviste y me parece una feature muy útil. Yo lo probé siempre desde Chrome.

**Comment by FdelMazo** [comment]
Gracias @Fxusto. Cierro el issue, si se te ocurren cosas para meterle no dudes en abrir otro. Gracias por la idea y por probarlo!

**Comment by julitaras** [comment]
Buenisimo Fede! Esta muy bueno el warning para que no se pisen los planes
