### ISSUE TITLE
Cuando edito el nombre del Plan (Plan #1, Plan #2) si coloco un espacio melo toma como finalizado

### ISSUE THREAD

**Issue by julitaras** [FdelMazo/FIUBA-Plan#60]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/30576222/184017767-5bdeb8ff-a18d-4aba-a93c-89e6894f1c2f.png">

Si quiero colocar varias palabra tengo que ir a editar varias veces lo cual es bastante tedioso

**Comment by FdelMazo** [comment]
Genial, cuando tenga tiempo lo veo. Tirame un PR julita no seas garca

**Comment by FdelMazo** [comment]
Bueno, el bug lo pude replicar... lo que no puedo es solucionarlo. La manera en la que `Tabs` usa la barra espaciadora hace que no podamos tocarla en `Editable`, ni siquiera clavando `event.stopPropagation()` (al menos en mis intentos).

Parece que no es la primera vez que surge! Hay que pegarle un ojo a este [issue](https://github.com/chakra-ui/chakra-ui/discussions/2557) de chakra-ui, aunque todo indica que no le van a dar mucha bola.

Me parece que lo mejor va a ser o dejar el bug y fue (a lo sumo es molesto ir y volver con la barra espaciadora, o cuando el usuario se da cuenta le clava guiones en vez de espacios), o intentar hacer a mano la funcionalidad de `<Tabs>` y cambiarlo por un `<Box>`. No se me ocurren otras cosas por ahora! Y no tengo mucho tiempo para priorizar esto en este momento

**Comment by julitaras** [comment]
En estos dia miro a ver que onda!

**Comment by FdelMazo** [comment]
Tal vez en vez de lograr que no se desfocusee, podemos hacer que tocar barra espaciadora re-focusee el input, cosa de que de manera imperceptible para el usuario parezca que no paso nada

**Comment by FdelMazo** [comment]
Solucionado acá!

2f5da9ab5395c1c7d6affe1ec75adfb1fc5826ab
