### ISSUE TITLE
Buscar materias por dia de la semana

### ISSUE THREAD

**Issue by tcastellano0** [FdelMazo/FIUBA-Plan#67]
Hola Fede, como va?
Una funcionalidad que me parece que resultaria util agregar, es que podamos buscar todas las materias que se cursan un Lunes, un Martes, etc. Es decir buscar las materias disponibles en ese dia, esto permitiria que cuando queremos llenar algun espacio en blanco de algun dia de la semana sea mas facil hacerlo.
Hoy en dia lo que me pasa, es que cuando quiero intentar agregar una materia un Martes (por ejemplo) tengo que ir probando materia por materia para llenar ese espacio y resultaria mas facil (creo yo) de alguna forma clickear en "Martes" y ver todos los cursos que tenes disponible para ese dia de la semana.

Avisame que pensas
Abrazo

**Comment by FdelMazo** [comment]
Hola Tomi!

Actualmente no estoy agregando features al repo, pero me parece una buena idea. Tal vez podemos dejarla un poco mas definida en este issue para que alguien que se lo cruce (o incluso vos) pueda implementarlo siguiendo la idea?

Lo que vos decis es que a la hora de elegir, por ejemplo, "simulación" del listado de materias, en algun lado te diga "se cursa solo los jueves", asi no tenes que probar mucho? Decis algo mas parecido a un menu dedicado a buscar solo por dias de semana? como te lo imaginas?

Tal vez es algo que solo funcionaria para materias de catedra unica? porque ponele, analisis matematico 2 se cursa los 5 dias de la semana si agarras catedras al azar, esa info no sirve mucho. 

O no se, tal vez algo como tenia el organizador de lugfi anterior, que te dejaba buscar compatibilidad entre planes?

Contame vos que pensabas!
