### ISSUE TITLE
Actualizacion 1C 2023

### ISSUE THREAD

**Issue by fransobral** [FdelMazo/FIUBA-Plan#68]
Hola Fede, como esatas? Me parece que no funciona mas la pagina ofertahorariafiuba. No se bien como es el tema de la actualizacion de catedras pero te avisaba por las dudas.

Gran trabajo el tuyo, abrazo!

**Comment by FdelMazo** [comment]
Hola Fran! Gracias por abrirme el issue. Si, lo de ofertahoraria es pésimo, el cuatri pasado me dijeron que "solo la actualizamos porque nos pediste", asi que ayer les mande un mail a secretaría académica pidiendo que la actualicen este cuatri de nuevo. 

Veremos si en la semana que viene se actualiza y listo, o si hay que buscar alguna otra forma de actualizar los horarios antes de que arranquen las fechas de inscripción. También es una cagada que justo se viene una semana corta.

Lo otro que pensaba hacer era, si no me dan bola antes del viernes que viene, poner algun cartelito en la app diciendo "manden mail a sec academica pidiendo que actualicen la pagina", pero creo que me van a terminar odiando por eso.

La única otra fuente de horarios es loguearse al SIU y abrir la lista de materias, pero para eso necesitaria una lista de materias _por cada carrera de fiuba_, que es una fiaca de pedir. El finde anterior a la inscripcion si no hay manera de hacer andar ofertahoraria, pido ayuda con eso...

Acepto cualquier idea que alguien tenga!

**Comment by fdelu** [comment]
Buenas @FdelMazo! Creo que ya lo actualizaron, puede ser?
![image](https://user-images.githubusercontent.com/71850278/219988568-52909720-0548-42eb-a73f-54f51013e341.png)

**Comment by FdelMazo** [comment]
Genio por verlo @fdelu! Ahí mande la action en #69, en unos minutos debería estar actualizada la página. Si ves todos los horarios correctos, @fransobral, cerras el issue?
