### ISSUE TITLE
Actualizar horarios antes de las 12

### ISSUE THREAD

**Issue by Maleriandro** [FdelMazo/FIUBA-Plan#74]
Viendo que recién ahora actualizaron la página de la oferta horaria, capaz se podría ejecutar prematuramente el workflow que agrega las materias, para tener un día más para organizarnos.

**Comment by fdelu** [comment]
@FdelMazo

**Comment by FdelMazo** [comment]
Impecable. Gracias por el mention! Casi me lo pierdo. Ahí lo corro

**Comment by FdelMazo** [comment]
Actualizado gracias a #73. Gracias por abrir el issue! 

En 5min deberia estar deployado. Si surge algun problema, no duden en abrirme otro issue. Abrazo!
