### ISSUE TITLE
Reagregar materias transición 

### ISSUE THREAD

**Issue by Maleriandro** [FdelMazo/FIUBA-Plan#81]
El commit https://github.com/FdelMazo/FIUBA-Plan/commit/94c44833687c8fd14df5fbcc93d07b7e2f2e8582 elimino las materias de la transición al plan nuevo. Habría que reagregarlas con la modificación de las descripciones.

A la noche o mañana podría llegar a modificarlo yo.

**Comment by FdelMazo** [comment]
Soy un boludo. Me olvide completamente! Ahí las agrego

**Comment by FdelMazo** [comment]
Pusheado en 2a8ca7ec838659e71b7f45654baa7f40f8a76a61

Si ves algo raro, abri un PR. Gracias!!
