### ISSUE TITLE
Planes nuevos?

### ISSUE THREAD

**Issue by FdelMazo** [FdelMazo/FIUBA-Plan#82]
Los planes nuevos traen muchas nuevas materias, que encima ya no tienen codigo numerico. Hay que adaptar el codigo que dependa de que las materias sean `xx.xx` a otra cosa, y tambien agregar las nuevas materias a las carreras...

Y ver que pinga hace ofertahoraria con las nuevas materias tambien!

**Comment by FdelMazo** [comment]
Hola @lopezac! Mas alla de las materias nuevas, la preocupacion con los horarios es que no hay ningun lugar donde esten todos juntos, no? https://ofertahoraria.fi.uba.ar/ no esta actualizado, y el SIU requiere autenticacion de cada usuario. Sin esos datos no se como puede seguir la aplicación viva. Tenes alguna idea/sugerencia?

**Comment by lopezac** [comment]
Lo ideal seria que [https://ofertahoraria.fi.uba.ar/](https://ofertahoraria.fi.uba.ar/) estubiera actualizado (prontamente tendria que estarlo esperemos).

Una solucion temporal seria hacer funcionar la aplicacion con estos [datos](https://pastebin.com/q3g5Mr5Z), que los saque entrando al siu guarani, yendo a oferta de comisiones y copiando todo (y agregando unos espacios para que sea mas legible, aunque para que funcione bien habria que copiarlo y pegarlo sin editar), y actualizar esos datos frecuentemente hasta que [https://ofertahoraria.fi.uba.ar/](https://ofertahoraria.fi.uba.ar/) este actualizado.

**Comment by FdelMazo** [comment]
Lo bueno: actualizaron ofertarhoraria -> https://github.com/FdelMazo/FIUBA-Plan/pull/85
Lo malo: no estan las materias de los planes nuevos, no??? hay que molestar a secretaria academica de nuevo?

**Comment by FdelMazo** [comment]
O tenes idea de si las materias que estan ahi son los horarios de las materias nuevas con los nombres viejos?

**Comment by lopezac** [comment]
Tenes razon los datos de mi pastebin solamente son de mi carrera y seria demasiado trabajo manual conseguir de todas las carreras.

Los horarios de ofertahoraria no concuerdan con los horarios del siu, asi que me parece que son de las materias viejas, lo unico que se me ocurre seria que secreteria academica actualice ofertahoraria con el plan 2020.

**Comment by FdelMazo** [comment]
Cerrado por #86 (y subsecuentes fixes)
