### ISSUE TITLE
Deprecar ofertahoraria

### ISSUE THREAD

**Issue by FdelMazo** [FdelMazo/FIUBA-Plan#88]
FIUBA cada vez le da menos bola a mantener actualizado ofertahoraria, lo que hace que sea cada vez mas lio tener al dia el fiuba plan cuatrimestre a cuatrimestre. Ahora que se pueden usar los horarios del SIU, hay que hacer que esa sea la funcionalidad principal del programa y listo.

Sacar todo lo que sea codigo referente a tener dos fuentes distintas de horarios, hacer mas grande y facil de entender lo de los horarios del siu, hacer que si no tenes horarios puestos cuando entras te aparezca el popup, hacer que no se pueda abrir el drawer sin horarios parseados (o directo reemplazar el boton con uno que tenga el loguito del SIU), dejar que la gente mande bugs con el archivo de parseo (o al menos apuntar al mail), etc etc etc

**Comment by lopezac** [comment]
Me parece perfecto lo que decis, este nuevo enfoque a la aplicacion de uno usarlo como una herramienta es mas sencillo de mantener ahora y a futuro, es mas facil mantener el parser del siu que bancar la api de ofertahoraria.

Esto tendria que ser hecho en la branch de manual-upload?, en otra branch, o directo en la branch master?
