### ISSUE TITLE
Materia Arq de Software faltante

### ISSUE THREAD

**Issue by Naza26** [FdelMazo/FIUBA-Plan#91]
Hola!

No sé si me pasa solo a mi pero cuando quise armar un plan, busqué la materia Arquitectura del Software, que entiendo es una optativa tanto en el plan viejo como en el nuevo de la carrera de Ing.Informática, no la encontré.
Si mal no recuerdo, el código de materia es 75.73.
Me cloné el repo y lo estuve debuggeando un cachito para ver que pasaba. Al principio pensé que faltaba del json de carreras pero después vi que el código de materia esta ahí efectivamente.
Asi que vi que cuando crea el dataContext que después consume el buscador, inicializa el source con horariosSiu ó jsonData (horarios), ahi mismo puse un log y vi que no viene la materia directamente (`source.materias.filter(materia => materia.codigo == "7573")`).
Intenté agregarla al json de horarios pensando que eso lo arreglaría pero no vi nada diferente. No sé si tengo que actualizar algo o estoy viendo en el lado correcto. Tampoco me queda claro que esto sea un problema para todos o que quizás sea un tema mío, levanto el issue por las dudas!

**Comment by FdelMazo** [comment]
Hola Nazaaa, gracias por el issue! El tema de arqui lo tengo que investigar a ver que estuvo fallando, pero mas alla de eso la idea es que en el futuro se saque del todo los horarios cuatrimestrales de la app y solo se tengan los del SIU cargados a manos (se puede ver en el PR abierto). Esto es porque los horarios de FIUBA son cada vez mas dificiles de conseguir y es mejor idea dejar de depender de servicios externos.

Despues de esos cambios y refactor me fijo si hay algun error relacionado a este issue que siga estando. Gracias por el issue!

**Comment by Naza26** [comment]
De nada Fede!

Perdón, quise ver de arreglarte el problema antes de cargarte el issue pero no pude.
Cualquier cosa que necesites ando por acá!

Beso

**Comment by Naza26** [comment]
Genial Fede, si tengo un rato lo chusmeo bien!
