### ISSUE TITLE
UBA-Plan

### ISSUE THREAD

**Issue by lopezac** [FdelMazo/FIUBA-Plan#98]
Hola @FdelMazo este proyecto siempre me parecio copado, y ahora que funciona con el SIU Guarani, creo que ahora se puede extender a toda la UBA, asi puede ayudar a mucha gente mas.

Aca consegui el [siu-usuario-exactas-computacion-primer-cuatri.txt](https://github.com/FdelMazo/FIUBA-Plan/files/14640414/siu-usuario-exactas-computacion-primer-cuatri.txt), texto de la pagina de una persona (entre en su siu-guarani exactas y copie todo) (cambie su nombre a "Nombre Falso" linea 4) que esta cursando el primer año (termino el cbc en 2023) de Ciencias de la Computacion en la facultad de exactas, y funciona hasta la parte de importar horarios, reconoce los periodos, luego cuando queres agregar una materia crashea.

Un detalle seria poner nuevas instrucciones, por ejemplo la pagina de oferta de comisiones de [FIUBA](https://guaraniautogestion.fi.uba.ar/g3w/oferta_comisiones) y [Exactas](https://inscripciones.exactas.uba.ar/autogestion/oferta_comisiones) tienen distinto dominio y formato.

**Comment by FdelMazo** [comment]
@lopezac, me parece alta idea, y me parece la evolución natural de la app (me encantaría ver a toda la UBA usando las herramientas como el fiuba map y el fiuba plan!), pero no se si yo personalmente puedo darle support a más facultades, por mis tiempos y mis ganas.

En cuanto al txt de exactas, el problema que tenía lo fixee en #100. El formato del SIU de exactas agrega la linea de "subcomisiones", que es algo que en fiuba no tenemos. Así que tuve que cambiar apenitas el parser. Decile a tu amigo que le recomiende la app a más gente de su facultad!

Lo que pienso es que de la misma forma que este siu tenia otro formato, los sius de otras facultades van a traer su propio tipo de problemas. Me parece que mientras mas escale la aplicación, más superficie de errores hay.

Me gusta la idea de que el parser sea lo mas todoterreno posible y se banque cualquier tipo de txt que le tiremos, pero no se si le cambiaría el nombre a la app para decir que le da support a otras facultades cuando todavía no lo hace ni se si pondría algo específico de exactas en el set de instrucciones de la herramienta.

Lo que me copa de que sea solo para FIUBA es que lo puedo testear facilmente yo. Si tengo que salir a buscar txts de otras facultades se hace un lio y un telefono descompuesto.

Tal vez se puede buscar un encare un poco más orgánico y depender del boca en boca? Por ejemplo, poner un cartelito que sea "esto funciona para sius de otras facultades, si tenes amigos de otros lados recomendalo" (etc). A medida que vayan cayendo sugerencias ("che soy de economicas y no me anda este txt"), ir arreglandolas.

No se bien como encararlo la verdad, se te ocurre algo?

**Comment by FdelMazo** [comment]
Lo cierro por ahora. Me parece que es intuitivo que si lee del SIU de FIUBA, tal vez lee de otros SIUs. Si van cayendo gente preguntando del tema veo de hacerlo mas explicito!
